# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Mella' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMella

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'CocoaMQTT'
pod 'QRCodeReader.swift'
pod 'Firebase/Database'

  target 'The MellaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The MellaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
